### ISSUE TITLE
action运行会被跳过

### ISSUE THREAD

**Issue by axcdxz** [GamerNoTitle/wyycg-autocheckin#3]
自动运行的脚本状态一直是Skipped  之前没用过GitHub的action 不知道怎么调整 很抱歉问这个问题

**Comment by GamerNoTitle** [comment]
```yaml
name: AutoCheckin

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 2 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # <== 删掉这一行
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements #安装轮子
      run: |
        pip install -r requirements.txt
    - name: Run script
      run: |
        python3 main.py "${{ secrets.cookie }}" "${{ secrets.teleid }}" "${{ secrets.teletoken }}" "${{ secrets.SCKEY }}" "${{ secrets.QQKEY }}" "${{ secrets.PPKEY }}"
```
把里面`if`的那一行删了就可以了
